#!/bin/bash

swww query || swww init

THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

if [ $THEMEIS == "dark.css" ]; then
  swww img ~/.config/hypr/wallpaper-dark.jpg
else
  swww img ~/.config/hypr/wallpaper.jpg
fi
